console.log('Hello');
var a=30;
console.log("The value of a is:"+a);
var a=30;
console.log("the new value of a is:" +a);
let b=15;
console.log("the value of b is:" +b);
b=25;
console.log("the updated value of b is "+b);
const c=40;
console.log("The value of c is:" +c);
c=45;
console.log("Updated value of c is"+ c);